name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: "a8e64ef7-de93-460e-bab9-c984d9b5ee78"
  ARM_CLIENT_SECRET: "PRL8Q~FWND2S5JODARQyRBLkN9X2ObAW7qJ.ZanL"
  ARM_SUBSCRIPTION_ID: "705d038c-7187-42ac-8cbf-06356d2c6647"
  ARM_TENANT_ID: "a9e24e7c-aca7-4fa6-b4e2-c82fe26352dc"

jobs:

###########################################################
# PR VALIDATION
###########################################################

  terraform-validation:

    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Parent Module

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      
      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Check Terraform formatting
      - name: Terraform Format
        run: terraform fmt -check

      # 6. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # 7. Create Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Apply Terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan